AWSTemplateFormatVersion: 2010-09-09
Description: Cloud9 For develop

# Metadata:

Parameters:
  SystemName:
    Type: String
    Default: develop
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prd]
    ConstraintDescription: must specify dev, stg or prd.
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedPattern: '^[a-z][1-9][.][a-z0-9]+$'

Mappings: 
  AzMap: 
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1d
      3rd: ap-northeast-1c

# Conditions

# Transform

Resources:
#  # Define for Cloud9 SecurityGroup
#  SecurityGroup:
#    Type: AWS::EC2::SecurityGroup
#    Properties:
#      GroupDescription: !Sub
#        - ${SystemName}-${EnvType}-cloud9
#        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#      GroupName: !Sub
#        - ${SystemName}-${EnvType}-cloud9
#        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#      SecurityGroupEgress: []
#      SecurityGroupIngress:
#        - IpProtocol: tcp
#          FromPort: 443
#          ToPort: 443
#          CidrIp:
#            Fn::ImportValue: !Sub
#              - ${SystemName}-${EnvType}-vpc-cidrblock
#              - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#      Tags:
#        - Key: SystemName
#          Value: !Ref SystemName
#        - Key: EnvType
#          Value: !Ref EnvType
#        - Key: Name
#          Value: !Sub
#            - sg-${SystemName}-${EnvType}-cloud9
#            - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#      VpcId:
#        Fn::ImportValue: !Sub
#          - ${SystemName}-${EnvType}-vpc
#          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#
#  VPCEndpointssm:
#    Type: AWS::EC2::VPCEndpoint
#    Properties:
#      PolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Action: "*"
#            Principal: "*"
#            Resource: "*"
#      PrivateDnsEnabled: true
#      RouteTableIds: []
#      SecurityGroupIds:
#        - !Ref SecurityGroup
#      ServiceName: com.amazonaws.ap-northeast-1.ssm
#      SubnetIds:
#        - Fn::ImportValue: !Sub
#           - ${SystemName}-${EnvType}-Private-subnet1
#           - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#        - Fn::ImportValue: !Sub
#           - ${SystemName}-${EnvType}-Private-subnet2
#           - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#      VpcEndpointType: Interface
#      VpcId:
#        Fn::ImportValue: !Sub
#          - ${SystemName}-${EnvType}-vpc
#          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#    DependsOn: SecurityGroup
#
#  VPCEndpointssmmessages:
#    Type: AWS::EC2::VPCEndpoint
#    Properties:
#      PolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Action: "*"
#            Principal: "*"
#            Resource: "*"
#      PrivateDnsEnabled: true
#      RouteTableIds: []
#      SecurityGroupIds:
#        - !Ref SecurityGroup
#      ServiceName: com.amazonaws.ap-northeast-1.ssmmessages
#      SubnetIds:
#        - Fn::ImportValue: !Sub
#           - ${SystemName}-${EnvType}-Private-subnet1
#           - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#        - Fn::ImportValue: !Sub
#           - ${SystemName}-${EnvType}-Private-subnet2
#           - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#      VpcEndpointType: Interface
#      VpcId:
#        Fn::ImportValue: !Sub
#          - ${SystemName}-${EnvType}-vpc
#          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#    DependsOn: SecurityGroup
#
#  VPCEndpointec2messages:
#    Type: AWS::EC2::VPCEndpoint
#    Properties:
#      PolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Action: "*"
#            Principal: "*"
#            Resource: "*"
#      PrivateDnsEnabled: true
#      RouteTableIds: []
#      SecurityGroupIds:
#        - !Ref SecurityGroup
#      ServiceName: com.amazonaws.ap-northeast-1.ec2messages
#      SubnetIds:
#        - Fn::ImportValue: !Sub
#           - ${SystemName}-${EnvType}-Private-subnet1
#           - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#        - Fn::ImportValue: !Sub
#           - ${SystemName}-${EnvType}-Private-subnet2
#           - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#      VpcEndpointType: Interface
#      VpcId:
#        Fn::ImportValue: !Sub
#          - ${SystemName}-${EnvType}-vpc
#          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
#    DependsOn: SecurityGroup

#  # Define Cloud9 Role
#  AWSCloud9SSMAccessRole:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service:
#              - cloud9.amazonaws.com
#              - ec2.amazonaws.com
#            Action:
#              - 'sts:AssumeRole'
#      Description: 'Service linked role for AWS Cloud9'
#      Path: '/service-role/'
#      ManagedPolicyArns: 
#        - arn:aws:iam::aws:policy/AWSCloud9SSMInstanceProfile
#      RoleName: 'AWSCloud9SSMAccessRole'

#AWSCloud9SSMInstanceProfile:
#  Type: AWS::IAM::InstanceProfile
#  Properties:
#    InstanceProfileName: AWSCloud9SSMInstanceProfile
#    Path: /cloud9/

#  AWSServiceRoleForAWSCloud9:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: 2012-10-17
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service:
#              - cloud9.amazonaws.com
#            Action:
#              - 'sts:AssumeRole'
#      Description: 'Service linked role for AWS Cloud9'
#      Path: '/aws-service-role/cloud9.amazonaws.com/'
#      ManagedPolicyArns:
#        - arn:aws:iam::aws:policy/aws-service-role/AWSCloud9ServiceRolePolicy
#      RoleName: 'AWSCloud9ServiceRolePolicy'
#    DependsOn: AWSCloud9SSMAccessRole

  # Define Cloud9
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: !Sub
        - ${SystemName}-${EnvType}-cloud9
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      ImageId: amazonlinux-2-x86_64
      InstanceType: !Ref InstanceType
      Name: !Sub
        - ${SystemName}-${EnvType}-cloud9
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      SubnetId:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-Public-subnet1
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      Tags:
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  Cloud9:
    Value: !GetAtt Cloud9.Arn
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-cloud9-arn
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
