AWSTemplateFormatVersion: 2010-09-09
Description: Cloud9 For develop

# Metadata:

Parameters:
  SystemName:
    Type: String
    Default: develop
    AllowedPattern: '[a-zA-Z0-9-]*'
  EnvType:
    Description: Environment type.
    Type: String
    Default: dev
    AllowedValues: [dev, stg, prd]
    ConstraintDescription: must specify dev, stg or prd.
  InstanceType:
    Type: String
    Default: t2.micro
    AllowedPattern: '^[a-z][1-9][.][a-z0-9]+$'

Mappings: 
  AzMap: 
    ap-northeast-1:
      1st: ap-northeast-1a
      2nd: ap-northeast-1d
      3rd: ap-northeast-1c

# Conditions

# Transform

Resources:
  # Define Cloud9 Role
  AWSManagedRoleForEC2:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Description: 'IAM Role for EC2'
      Path: '/'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
      RoleName: 'AWSManagedRoleForEC2'

  IAMInstanceProfileAWSManagedRoleForEC2:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Path: "/"
      InstanceProfileName: !Ref AWSManagedRoleForEC2
      Roles:
        - !Ref AWSManagedRoleForEC2

  # Define Cloud9
  Cloud9:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: !Sub
        - ${SystemName}-${EnvType}-cloud9
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      ImageId: amazonlinux-2-x86_64
      InstanceType: !Ref InstanceType
      Name: !Sub
        - ${SystemName}-${EnvType}-cloud9
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      SubnetId:
        Fn::ImportValue: !Sub
          - ${SystemName}-${EnvType}-Public-subnet1
          - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
      Tags:
        - Key: SystemName
          Value: !Ref SystemName
        - Key: EnvType
          Value: !Ref EnvType

Outputs:
  Cloud9:
    Value: !GetAtt Cloud9.Arn
    Export:
      Name: !Sub
        - ${SystemName}-${EnvType}-cloud9-arn
        - {SystemName: !Ref SystemName, EnvType: !Ref EnvType}
